package goaLegislativeAssembly;

//AUTHOR NAME: LAXMI CHARI
//ROLL NO: 22
//TITLE: IMITATION OF GOA LEGISLATIVE ASSEMBLY
//START DATE: 15/072024
//MODIFIED DATE: 22/07/2024
//DESCRIPTION: THIS IS AN ABSTRACT CLASS TO BE EXTENDED BY FOLLOWING CLASSES IN THIS PROJECT 

public abstract class Entity {
  @Override
  public abstract String toString();
}